### ISSUE TITLE
ERROR IN Adding custom pages & URLs

### ISSUE THREAD

**Issue by zangguojun** [oTree-org/oTree#81]
**AttributeError: 'function' object has no attribute 'url_pattern'**
"from otree.urls import urlpatterns" ---- Is something wrong here?

Haven't your official documents been updated?

**Comment by oTree-org** [comment]
Hi, can you show your code, traceback, and otree version? I just tested the instructions [here](https://otree.readthedocs.io/en/latest/misc/django.html) and it works fine for me.

**Comment by zangguojun** [comment]
setting.py:
ROOT_URLCONF = "trust.url"

pages.py:
def my_view(request):
    return render(request,'trust/Rules.html')

url.py:
from django.urls import path
from otree.urls import urlpatterns
import trust.pages

urlpatterns.append(
    path('my_view/', trust.pages.my_view)
)

**Comment by oTree-org** [comment]
I also need the traceback and otree version, thank you.

**Comment by zangguojun** [comment]
> I also need the traceback and otree version, thank you.
version : 3.2.4
traceback :

Traceback (most recent call last):
  File "C:\Users\buchiyu\AppData\Roaming\Python\Python37\site-packages\otree\management\commands\devserver.py", li
ne 112, in handle
    self.check(display_num_errors=True)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "b:\anaconda3\envs\otree\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "b:\anaconda3\envs\otree\lib\site-packages\django\urls\resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "b:\anaconda3\envs\otree\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\urls\resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "b:\anaconda3\envs\otree\lib\site-packages\django\urls\resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "b:\anaconda3\envs\otree\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Desktop\trust\trust\url.py", line 2, in <module>
    from otree.urls import urlpatterns
  File "C:\Users\buchiyu\AppData\Roaming\Python\Python37\site-packages\otree\urls.py", line 211, in <module>
    urlpatterns = get_urlpatterns()
  File "C:\Users\buchiyu\AppData\Roaming\Python\Python37\site-packages\otree\urls.py", line 166, in get_urlpattern
s
    urlpatterns += url_patterns_from_app_pages(views_module.__name__, name_in_url)
  File "C:\Users\buchiyu\AppData\Roaming\Python\Python37\site-packages\otree\urls.py", line 64, in url_patterns_fr
om_app_pages
    url_pattern = ViewCls.url_pattern(name_in_url)
AttributeError: 'function' object has no attribute 'url_pattern'

**Comment by oTree-org** [comment]
Sorry for the late reply; I didn't see the update. Anyway it looks like you put your `my_view` function in your page_sequence? it is not supposed to be there.

**Comment by zangguojun** [comment]
> Sorry for the late reply; I didn't see the update. Anyway it looks like you put your `my_view` function in your page_sequence? it is not supposed to be there.

Thank you for your reply
I know but  in your official documents:
```
# In my_app.pages
from django.http import HttpResponse

def my_view(request):
    return HttpResponse('This is a custom view')
```
and I didn't put `my_view ` in `page_sequence = []` seeeeing:

```
def my_view(request):
    return render(request,'trust/Rules.html')
class A_Task(Page):
    pass
class B_Task(Page):
    pass
class C_Task(Page):
    pass
# ...
page_sequence = [
    A_Task,
    B_Task,
    C_Task,
    # ...
]
```
AND I don't know what  **_In my_app.pages_** means, so I misinterpreted it and put them in pages.py
Where do I need to put `my_view`

Looking forward to your solution.

**Comment by oTree-org** [comment]
Can you show your full page_sequence? (You put the `# ...` so I guess there is more.) There must be something in there that is not a Page or WaitPage.

**Comment by oTree-org** [comment]
And check all your other apps.

**Comment by zangguojun** [comment]
> Can you show your full page_sequence? (You put the `# ...` so I guess there is more.) There must be something in there that is not a Page or WaitPage.

Oh , this is my mistake, there  also has `my_view ` in it .
**What I actually want to do now is :**
I have two types of participants **boys and girls** .There are two people in each group, one boy and one gril and I **hope** that I can **distinguish** which `URL` are boys and which are girls, just like
http://localhost:8000/**boy**/3v88gzlg
http://localhost:8000/**gril**/sbbaqi9x
NOT http://localhost:8000/**InitializeParticipant**/3v88gzlg
**InitializeParticipant** couldn't tell the gender of the participants
SO 👍 How do I need to change my code?

**Comment by oTree-org** [comment]
you should pre-assign participants to labels: https://otree.readthedocs.io/en/latest/rooms.html#pre-assigning-participants-to-labels

**Comment by zangguojun** [comment]
> you should pre-assign participants to labels: https://otree.readthedocs.io/en/latest/rooms.html#pre-assigning-participants-to-labels

No！You've misinterpreted what I mean. I want to divide all participants into two categories and the url is used to distinguish between these two types(boys and girls) of participants, not each participants
