### ISSUE TITLE
Problems of otree deployment on heroku

### ISSUE THREAD

**Issue by zangguojun** [oTree-org/oTree#85]
Otree has been suspended in `creating_ session ` page
But there is no problem with otree running in localhost.
Attention:
public_pool : project_name
E:\Desktop\otree\public_pool : local place

**heroku‘s log:**
```
2020-11-29T08:57:42.133119+00:00 app[web.1]: 
2020-11-29T08:57:42.133119+00:00 app[web.1]: Traceback (most recent call last):
2020-11-29T08:57:42.133120+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/run.py", line 89, in _server_callback
2020-11-29T08:57:42.133120+00:00 app[web.1]:     await TCPServer(app, loop, config, reader, writer)
2020-11-29T08:57:42.133121+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 86, in run
2020-11-29T08:57:42.133121+00:00 app[web.1]:     await self._close()
2020-11-29T08:57:42.133122+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 132, in _close
2020-11-29T08:57:42.133122+00:00 app[web.1]:     await self.writer.wait_closed()
2020-11-29T08:57:42.133122+00:00 app[web.1]: AttributeError: 'StreamWriter' object has no attribute 'wait_closed'
2020-11-29T08:57:42.136908+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/create_demo_session/" host=public1pool.herokuapp.com request_id=cfe9edd0-6745-4e21-bc73-d14d43fec61c fwd="140.238.17.91" dyno=web.1 connect=1ms service=2ms status=503 bytes=0 protocol=https
2020-11-29T08:59:32.256716+00:00 app[web.1]: ERROR Task exception was never retrieved
2020-11-29T08:59:32.256743+00:00 app[web.1]: future: <Task finished coro=<worker_serve.<locals>._server_callback() done, defined at /app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/run.py:88> exception=AttributeError("'StreamWriter' object has no attribute 'wait_closed'",)>
2020-11-29T08:59:32.256744+00:00 app[web.1]: Traceback (most recent call last):
2020-11-29T08:59:32.256745+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/run.py", line 89, in _server_callback
2020-11-29T08:59:32.256746+00:00 app[web.1]:     await TCPServer(app, loop, config, reader, writer)
2020-11-29T08:59:32.256747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 86, in run
2020-11-29T08:59:32.256748+00:00 app[web.1]:     await self._close()
2020-11-29T08:59:32.256748+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 132, in _close
2020-11-29T08:59:32.256749+00:00 app[web.1]:     await self.writer.wait_closed()
2020-11-29T08:59:32.256756+00:00 app[web.1]: AttributeError: 'StreamWriter' object has no attribute 'wait_closed'
2020-11-29T09:00:02.149197+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/create_demo_session/" host=public1pool.herokuapp.com request_id=ad29922a-d6a8-44e2-ab6a-e1df63fa211a fwd="140.238.17.91" dyno=web.1 connect=0ms service=3ms status=503 bytes=0 protocol=https
2020-11-29T09:00:02.145954+00:00 app[web.1]: ERROR Task exception was never retrieved
2020-11-29T09:00:02.145965+00:00 app[web.1]: future: <Task finished coro=<worker_serve.<locals>._server_callback() done, defined at /app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/run.py:88> exception=AttributeError("'StreamWriter' object has no attribute 'wait_closed'",)>
2020-11-29T09:00:02.145966+00:00 app[web.1]: Traceback (most recent call last):
2020-11-29T09:00:02.145969+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 82, in run
2020-11-29T09:00:02.145970+00:00 app[web.1]:     await self._read_data()
2020-11-29T09:00:02.145971+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/task_group.py", line 24, in __aexit__
2020-11-29T09:00:02.145971+00:00 app[web.1]:     await task
2020-11-29T09:00:02.145972+00:00 app[web.1]: concurrent.futures._base.CancelledError
2020-11-29T09:00:02.145972+00:00 app[web.1]: 
2020-11-29T09:00:02.145973+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-11-29T09:00:02.145973+00:00 app[web.1]: 
2020-11-29T09:00:02.145973+00:00 app[web.1]: Traceback (most recent call last):
2020-11-29T09:00:02.145974+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/run.py", line 89, in _server_callback
2020-11-29T09:00:02.145974+00:00 app[web.1]:     await TCPServer(app, loop, config, reader, writer)
2020-11-29T09:00:02.145975+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 86, in run
2020-11-29T09:00:02.145975+00:00 app[web.1]:     await self._close()
2020-11-29T09:00:02.145975+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/hypercorn_otree/asyncio/tcp_server.py", line 132, in _close
2020-11-29T09:00:02.145976+00:00 app[web.1]:     await self.writer.wait_closed()
2020-11-29T09:00:02.145982+00:00 app[web.1]: AttributeError: 'StreamWriter' object has no attribute 'wait_closed'
```
heroku commit log:
```
[master 11a47cc] make it better
 1 file changed, 2 insertions(+), 2 deletions(-)

E:\Desktop\otree\public_pool>git push heroku master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 370 bytes | 370.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> No change in requirements detected, installing from cache
remote: -----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote: -----> $ python manage.py collectstatic --noinput
remote:        34 static files copied to '/tmp/build_50ab5b57/__temp_static_root', 72 post-processed.
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web, worker
remote:
remote: -----> Compressing...
remote:        Done: 52.5M
remote: -----> Launching...
remote:        Released v9
remote:        https://public0pool.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/public0pool.git
   eadfec8..11a47cc  master -> master

E:\Desktop\otree\public_pool>git init
Reinitialized existing Git repository in E:/Desktop/otree/public_pool/.git/

E:\Desktop\otree\public_pool>heroku git:remote -a public0pool
set git remote heroku to https://git.heroku.com/public0pool.git

E:\Desktop\otree\public_pool>git add .

E:\Desktop\otree\public_pool>git commit -am "make it better"
On branch master
nothing to commit, working tree clean

E:\Desktop\otree\public_pool>git push heroku master
Everything up-to-date

E:\Desktop\otree\public_pool>heroku git:remote -a public1pool
set git remote heroku to https://git.heroku.com/public1pool.git

E:\Desktop\otree\public_pool>git add .

E:\Desktop\otree\public_pool>git commit -am "make it better"
On branch master
nothing to commit, working tree clean

E:\Desktop\otree\public_pool>git push heroku master
Enumerating objects: 154, done.
Counting objects: 100% (154/154), done.
Delta compression using up to 12 threads
Compressing objects: 100% (126/126), done.
Writing objects: 100% (154/154), 28.59 KiB | 1.36 MiB/s, done.
Total 154 (delta 65), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing python-3.6.12
remote: -----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting otree>=2.1.28
remote:          Downloading otree-3.3.6-py3-none-any.whl (582 kB)
remote:        Collecting psycopg2>=2.5.1
remote:          Downloading psycopg2-2.8.6.tar.gz (383 kB)
remote:        Collecting colorama==0.4.1
remote:          Downloading colorama-0.4.1-py2.py3-none-any.whl (15 kB)
remote:        Collecting priority
remote:          Downloading priority-1.3.0-py2.py3-none-any.whl (11 kB)
remote:        Collecting dj-database-url==0.5.0
remote:          Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
remote:        Collecting h2>=3.1.0
remote:          Downloading h2-4.0.0-py3-none-any.whl (57 kB)
remote:        Collecting typing-extensions
remote:          Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
remote:        Collecting whitenoise==4.1.3
remote:          Downloading whitenoise-4.1.3-py2.py3-none-any.whl (20 kB)
remote:        Collecting wsproto>=0.14.0
remote:          Downloading wsproto-1.0.0-py3-none-any.whl (24 kB)
remote:        Collecting asgiref==3.2.7
remote:          Downloading asgiref-3.2.7-py2.py3-none-any.whl (19 kB)
remote:        Collecting django-vanilla-views==1.0.6
remote:          Downloading django_vanilla_views-1.0.6-py2.py3-none-any.whl (8.9 kB)
remote:        Collecting toml
remote:          Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
remote:        Collecting termcolor==1.1.0
remote:          Downloading termcolor-1.1.0.tar.gz (3.9 kB)
remote:        Collecting h11
remote:          Downloading h11-0.11.0-py2.py3-none-any.whl (54 kB)
remote:        Collecting pytz==2019.2
remote:          Downloading pytz-2019.2-py2.py3-none-any.whl (508 kB)
remote:        Collecting Django==2.2.12
remote:          Downloading Django-2.2.12-py3-none-any.whl (7.5 MB)
remote:        Collecting hpack<5,>=4.0
remote:          Downloading hpack-4.0.0-py3-none-any.whl (32 kB)
remote:        Collecting hyperframe<7,>=6.0
remote:          Downloading hyperframe-6.0.0-py3-none-any.whl (11 kB)
remote:        Collecting dataclasses; python_version < "3.7"
remote:          Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
remote:        Collecting sqlparse
remote:          Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
remote:        Building wheels for collected packages: psycopg2, termcolor
remote:          Building wheel for psycopg2 (setup.py): started
remote:          Building wheel for psycopg2 (setup.py): finished with status 'done'
remote:          Created wheel for psycopg2: filename=psycopg2-2.8.6-cp36-cp36m-linux_x86_64.whl size=447569 sha256=4f93db4697239c47b91826be4834616862e7119069268cd9d956b366bc3eec58
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-z_x7c013/wheels/cb/74/1b/4b65077db4eb0d85763050e60c5921398d2858945558352dd8
remote:          Building wheel for termcolor (setup.py): started
remote:          Building wheel for termcolor (setup.py): finished with status 'done'
remote:          Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=d95b2e7b2013b417586366ee84ca6d0c943257610ce446b6624716ebb3f21a69
remote:          Stored in directory: /tmp/pip-ephem-wheel-cache-z_x7c013/wheels/93/2a/eb/e58dbcbc963549ee4f065ff80a59f274cc7210b6eab962acdc
remote:        Successfully built psycopg2 termcolor
remote:        Installing collected packages: colorama, priority, dj-database-url, hpack, hyperframe, h2, typing-extensions, whitenoise, h11, dataclasses, wsproto, asgiref, django-vanilla-views, toml, termcolor, pytz, sqlparse, Django, otree, psycopg2
remote:        Successfully installed Django-2.2.12 asgiref-3.2.7 colorama-0.4.1 dataclasses-0.8 dj-database-url-0.5.0 django-vanilla-views-1.0.6 h11-0.11.0 h2-4.0.0 hpack-4.0.0 hyperframe-6.0.0 otree-3.3.6 priority-1.3.0 psycopg2-2.8.6 pytz-2019.2 sqlparse-0.4.1 termcolor-1.1.0 toml-0.10.2 typing-extensions-3.7.4.3 whitenoise-4.1.3 wsproto-1.0.0
remote: -----> $ python manage.py collectstatic --noinput
remote:        34 static files copied to '/tmp/build_318f94ad/__temp_static_root', 72 post-processed.
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web, worker
remote:
remote: -----> Compressing...
remote:        Done: 52.4M
remote: -----> Launching...
remote:        Released v5
remote:        https://public1pool.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/public1pool.git
 * [new branch]      master -> master
```

**Comment by oTree-org** [comment]
looks like a python 3.6 issue. add a runtime.txt as described in heroku docs to ensure python 3.7 gets installed.
